// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ESSENTIA_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_ESSENTIA_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace ImpresarioSerialization {

struct Essentia;
struct EssentiaBuilder;

struct Essentia FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EssentiaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STFT = 4,
    VT_EQUALIZED = 6
  };
  const flatbuffers::Vector<float> *stft() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_STFT);
  }
  const flatbuffers::Vector<float> *equalized() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_EQUALIZED);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STFT) &&
           verifier.VerifyVector(stft()) &&
           VerifyOffset(verifier, VT_EQUALIZED) &&
           verifier.VerifyVector(equalized()) &&
           verifier.EndTable();
  }
};

struct EssentiaBuilder {
  typedef Essentia Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_stft(flatbuffers::Offset<flatbuffers::Vector<float>> stft) {
    fbb_.AddOffset(Essentia::VT_STFT, stft);
  }
  void add_equalized(flatbuffers::Offset<flatbuffers::Vector<float>> equalized) {
    fbb_.AddOffset(Essentia::VT_EQUALIZED, equalized);
  }
  explicit EssentiaBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Essentia> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Essentia>(end);
    return o;
  }
};

inline flatbuffers::Offset<Essentia> CreateEssentia(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> stft = 0,
    flatbuffers::Offset<flatbuffers::Vector<float>> equalized = 0) {
  EssentiaBuilder builder_(_fbb);
  builder_.add_equalized(equalized);
  builder_.add_stft(stft);
  return builder_.Finish();
}

inline flatbuffers::Offset<Essentia> CreateEssentiaDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *stft = nullptr,
    const std::vector<float> *equalized = nullptr) {
  auto stft__ = stft ? _fbb.CreateVector<float>(*stft) : 0;
  auto equalized__ = equalized ? _fbb.CreateVector<float>(*equalized) : 0;
  return ImpresarioSerialization::CreateEssentia(
      _fbb,
      stft__,
      equalized__);
}

inline const ImpresarioSerialization::Essentia *GetEssentia(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::Essentia>(buf);
}

inline const ImpresarioSerialization::Essentia *GetSizePrefixedEssentia(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::Essentia>(buf);
}

inline bool VerifyEssentiaBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::Essentia>(nullptr);
}

inline bool VerifySizePrefixedEssentiaBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::Essentia>(nullptr);
}

inline void FinishEssentiaBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Essentia> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEssentiaBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Essentia> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_ESSENTIA_IMPRESARIOSERIALIZATION_H_
