input_endpoint: ipc:///tmp/percipia
volitia_endpoint: tcp://volitia:44440

# lens 87
# keyhole 296
promenade_size: 296

initial_brightness: 10
max_brightness: 255

# ada for apa102's
# waldo for ws2812's
strip_name: waldo

####
# ada options
########
baud: 512000

####
# waldo options
########
# channel 0 is gpio 18, channel 1 is gpio 13
pwm_channel: 1
# use channel 10 for pi A/B, channel 11 for pi zero
dma_channel: 10
# if flickering occurs, try throttling refresh rate to ledCount * 30
refresh_rate: 2500
