# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Axiomology(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Axiomology()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAxiomology(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Axiomology
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Axiomology
    def Axioms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Axiomology
    def AxiomsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Axiomology
    def AxiomsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axiomology
    def AxiomsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def AxiomologyStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddAxioms(builder, axioms): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(axioms), 0)
def AxiomologyAddAxioms(builder, axioms):
    """This method is deprecated. Please switch to AddAxioms."""
    return AddAxioms(builder, axioms)
def StartAxiomsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AxiomologyStartAxiomsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartAxiomsVector(builder, numElems)
def End(builder): return builder.EndObject()
def AxiomologyEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)