# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

class Identifier(object):
    axiomology = 0
    essentia = 1
    glimpse = 2
    phenomenon = 3

