# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Essentia(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Essentia()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEssentia(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Essentia
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Essentia
    def Stft(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Essentia
    def StftAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Essentia
    def StftLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Essentia
    def StftIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Essentia
    def Equalized(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Essentia
    def EqualizedAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Essentia
    def EqualizedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Essentia
    def EqualizedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Start(builder): builder.StartObject(2)
def EssentiaStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddStft(builder, stft): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stft), 0)
def EssentiaAddStft(builder, stft):
    """This method is deprecated. Please switch to AddStft."""
    return AddStft(builder, stft)
def StartStftVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def EssentiaStartStftVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartStftVector(builder, numElems)
def AddEqualized(builder, equalized): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(equalized), 0)
def EssentiaAddEqualized(builder, equalized):
    """This method is deprecated. Please switch to AddEqualized."""
    return AddEqualized(builder, equalized)
def StartEqualizedVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def EssentiaStartEqualizedVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartEqualizedVector(builder, numElems)
def End(builder): return builder.EndObject()
def EssentiaEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)