# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IdentifierWrapper(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IdentifierWrapper()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIdentifierWrapper(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IdentifierWrapper
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IdentifierWrapper
    def Identifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(1)
def IdentifierWrapperStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddIdentifier(builder, identifier): builder.PrependInt8Slot(0, identifier, 0)
def IdentifierWrapperAddIdentifier(builder, identifier):
    """This method is deprecated. Please switch to AddIdentifier."""
    return AddIdentifier(builder, identifier)
def End(builder): return builder.EndObject()
def IdentifierWrapperEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)