# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Phenomenon(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Phenomenon()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPhenomenon(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Phenomenon
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Phenomenon
    def Identity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Phenomenon
    def Quantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(2)
def PhenomenonStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddIdentity(builder, identity): builder.PrependInt32Slot(0, identity, 0)
def PhenomenonAddIdentity(builder, identity):
    """This method is deprecated. Please switch to AddIdentity."""
    return AddIdentity(builder, identity)
def AddQuantity(builder, quantity): builder.PrependFloat32Slot(1, quantity, 0.0)
def PhenomenonAddQuantity(builder, quantity):
    """This method is deprecated. Please switch to AddQuantity."""
    return AddQuantity(builder, quantity)
def End(builder): return builder.EndObject()
def PhenomenonEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)